DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS role;

CREATE TABLE users (
  users_id BIGINT AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  CONSTRAINT USERS_PK PRIMARY KEY(users_id),
  CONSTRAINT USERS_UK_NAME UNIQUE(name)
);

CREATE TABLE role (
  role_id BIGINT AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(45) NOT NULL,
  CONSTRAINT ROLE_PK PRIMARY KEY(role_id),
  CONSTRAINT ROLE_UK_NAME UNIQUE(name)
);
